/**
 * City Silo Page Template - 11-Section Anti-Doorway Architecture
 *
 * ANTI-DOORWAY PRINCIPLE: The first 600-800 words of body text MUST be unique.
 * Sections 1-3 (Hero+CityIntro, CityRiskFactors, CityScleralBenefits) achieve this
 * through city-type-aware content differentiation across 10 city types.
 *
 * SECTION ORDER:
 * 1.  Hero Section (enhanced with CityIntroSection content)
 * 2.  CityRiskFactors — Dimension 1 unique content (100-150 words)
 * 3.  CityScleralBenefits — Dimension 2 unique content (150-200 words)
 * 4.  Neighborhoods Section — KEPT from original (conditional)
 * 5.  CityTestimonials — Dimension 3 patient experiences
 * 6.  Why Choose Us + CityPrevalence — KEPT with supporting data
 * 7.  CityCommuteSection — Replaces generic map section
 * 8.  CityFAQSection — Visible FAQ accordion with schema
 * 9.  CityInsuranceSection — Replaces generic insurance
 * 10. Lead Form — KEPT from original
 * 11. KeratoconusEducationSnippet — Links to resources
 */

import { Metadata } from 'next';
import { notFound } from 'next/navigation';
import { soCalCities } from '@/data/cities';
import Script from 'next/script';
import { MapPin, CheckCircle, Star, Shield, Clock, Eye } from 'lucide-react';

// City Silo Components (8 anti-doorway sections)
import CityIntroSection from '@/components/city-silos/CityIntroSection';
import CityRiskFactors from '@/components/city-silos/CityRiskFactors';
import CityScleralBenefits from '@/components/city-silos/CityScleralBenefits';
import CityTestimonials from '@/components/city-silos/CityTestimonials';
import CityPrevalence from '@/components/city-silos/CityPrevalence';
import CityCommuteSection from '@/components/city-silos/CityCommuteSection';
import CityFAQSection from '@/components/city-silos/CityFAQSection';
import CityInsuranceSection from '@/components/city-silos/CityInsuranceSection';
import KeratoconusEducationSnippet from '@/components/city-silos/KeratoconusEducationSnippet';

// Existing components
import LeadForm from '@/components/LeadForm';

interface Props {
    params: Promise<{
        city: string;
    }>;
}

// 1. Generate Static Params for all cities (SSG)
export async function generateStaticParams() {
    return soCalCities.map((city) => ({
        city: city.slug,
    }));
}

// 2. Dynamic Metadata
export async function generateMetadata({ params }: Props): Promise<Metadata> {
    const resolvedParams = await params;
    const city = soCalCities.find((c) => c.slug === resolvedParams.city);
    if (!city) return {};

    return {
        title: `Keratoconus Doctor ${city.name} | Same-Week Appts`,
        description: `${city.name}: skip the 6-month wait. 500+ keratoconus cases, 35+ yrs, direct specialist access. Insurance accepted. (714) 558-0641`,
        alternates: {
            canonical: `https://keratocones.com/locations/${city.slug}`,
        },
        openGraph: {
            title: `Keratoconus Doctor ${city.name} | Same-Week Appts`,
            description: `${city.name}: skip the 6-month wait. 500+ keratoconus cases, 35+ yrs, direct specialist access. Insurance accepted. (714) 558-0641`,
        },
    };
}

// 3. Page Component - 11-Section Anti-Doorway Architecture
export default async function CityPage({ params }: Props) {
    const resolvedParams = await params;
    const city = soCalCities.find((c) => c.slug === resolvedParams.city);

    if (!city) {
        notFound();
    }

    // Schema: MedicalBusiness (FAQPage schema is now generated by CityFAQSection)
    const businessSchema = {
        "@context": "https://schema.org",
        "@type": "MedicalBusiness",
        "name": "Keratoconus Vision Center | Dr. Alexander Bonakdar",
        "image": "https://keratocones.com/images/drbonakdar.webp",
        "priceRange": "$$",
        "telephone": "(714) 558-0641",
        "address": {
            "@type": "PostalAddress",
            "streetAddress": "801 N Tustin Ave #401",
            "addressLocality": "Santa Ana",
            "addressRegion": "CA",
            "postalCode": "92705",
            "addressCountry": "US"
        },
        "areaServed": {
            "@type": "City",
            "name": city.name,
            "address": {
                "@type": "PostalAddress",
                "addressRegion": "CA",
                "addressCountry": "US"
            }
        },
        "url": `https://keratocones.com/locations/${city.slug}`
    };

    return (
        <>
            <Script
                id="city-schema"
                type="application/ld+json"
                dangerouslySetInnerHTML={{ __html: JSON.stringify(businessSchema) }}
            />

            {/* ================================================================ */}
            {/* SECTION 1: Hero + CityIntroSection                               */}
            {/* ~150-200 unique words (city-type-aware intro paragraph)           */}
            {/* ================================================================ */}
            <CityIntroSection
                citySlug={city.slug}
                cityName={city.name}
                county={city.county}
            />

            {/* ================================================================ */}
            {/* SECTION 2: CityRiskFactors                                       */}
            {/* ~100-150 unique words (environmental + demographic risk factors)  */}
            {/* ================================================================ */}
            <CityRiskFactors
                citySlug={city.slug}
                cityName={city.name}
            />

            {/* ================================================================ */}
            {/* SECTION 3: CityScleralBenefits                                   */}
            {/* ~150-200 unique words (lifestyle-specific lens benefits)          */}
            {/* TOTAL UNIQUE CONTENT BY THIS POINT: 400-550 words                */}
            {/* ================================================================ */}
            <CityScleralBenefits
                citySlug={city.slug}
                cityName={city.name}
            />

            {/* ================================================================ */}
            {/* SECTION 4: Neighborhoods (conditional - only if city has them)    */}
            {/* KEPT from original template                                       */}
            {/* ================================================================ */}
            {city.neighborhoods && city.neighborhoods.length > 0 && (
                <section className="py-16 bg-white border-t border-gray-100">
                    <div className="container mx-auto px-4">
                        <h2 className="text-3xl font-serif font-bold text-eyecare-navy mb-6 text-center">
                            Serving Neighborhoods Throughout {city.name}
                        </h2>
                        <p className="text-lg text-gray-600 max-w-3xl mx-auto text-center mb-12">
                            Whether you live in {city.neighborhoods[0]}, {city.neighborhoods[1]}, or anywhere else in {city.name}, our specialized keratoconus care is just a short drive away.
                            We understand that finding a true scleral lens specialist can be challenging—many patients from {city.name} have been told to &ldquo;just live with it&rdquo; by general optometrists.
                            Dr. Bonakdar&apos;s practice exists specifically for complex corneal cases, and patients from across {city.county} trust us with their vision restoration journey.
                        </p>
                        <div className="grid grid-cols-2 md:grid-cols-3 gap-4 max-w-4xl mx-auto">
                            {city.neighborhoods.map((neighborhood) => (
                                <div key={neighborhood} className="bg-eyecare-lighter-blue/30 p-5 rounded-xl border border-eyecare-blue/10 text-center hover:border-eyecare-blue/30 hover:shadow-md transition-all">
                                    <h3 className="font-bold text-eyecare-navy text-sm">{neighborhood}</h3>
                                    <p className="text-xs text-gray-500 mt-1">Keratoconus care available</p>
                                </div>
                            ))}
                        </div>
                    </div>
                </section>
            )}

            {/* ================================================================ */}
            {/* SECTION 5: CityTestimonials                                      */}
            {/* Patient experiences tailored to city type                         */}
            {/* ================================================================ */}
            <CityTestimonials
                citySlug={city.slug}
                cityName={city.name}
            />

            {/* ================================================================ */}
            {/* SECTION 6: Why Choose Us + CityPrevalence                        */}
            {/* KEPT from original with prevalence data as supporting evidence    */}
            {/* ================================================================ */}
            <section className="py-20 bg-white">
                <div className="container mx-auto px-4">
                    <div className="max-w-5xl mx-auto">
                        <h2 className="text-3xl md:text-4xl font-serif font-bold text-eyecare-navy mb-6 text-center">
                            Why {city.name} Patients Choose Dr. Bonakdar
                        </h2>
                        <p className="text-lg text-gray-600 max-w-3xl mx-auto text-center mb-12">
                            When it comes to keratoconus, experience matters. Many patients arrive at our office after being told to &ldquo;just live with it&rdquo; or after failing lens fits at general optometry practices.
                        </p>

                        <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
                            {[
                                {
                                    icon: <Star className="w-6 h-6" />,
                                    title: "500+ Keratoconus Cases",
                                    desc: "Dr. Bonakdar has successfully fitted scleral and specialty lenses for over 500 keratoconus patients, including many of the most complex cases in the region."
                                },
                                {
                                    icon: <Shield className="w-6 h-6" />,
                                    title: "35+ Years Experience",
                                    desc: "With more than three decades of corneal specialty practice, Dr. Bonakdar has the depth of experience that only comes from treating thousands of patients."
                                },
                                {
                                    icon: <Clock className="w-6 h-6" />,
                                    title: "No 3-6 Month Wait",
                                    desc: "Unlike university eye centers where keratoconus consultations take months to schedule, we offer same-week appointments with direct specialist access."
                                },
                                {
                                    icon: <Eye className="w-6 h-6" />,
                                    title: "Direct Specialist Access",
                                    desc: "You see Dr. Bonakdar at every visit. Your care is not delegated to rotating residents or fellows. One doctor, consistent care, every time."
                                },
                                {
                                    icon: <CheckCircle className="w-6 h-6" />,
                                    title: "CHOC & UCI Referral Center",
                                    desc: "Our practice receives referrals from Children's Hospital of Orange County and UCI Medical Center for complex corneal cases requiring specialized expertise."
                                },
                                {
                                    icon: <MapPin className="w-6 h-6" />,
                                    title: "Central OC Location",
                                    desc: `Conveniently located in Santa Ana, accessible from ${city.name} via multiple freeways. Free parking available. Most visits completed in 60-90 minutes.`
                                }
                            ].map((item, i) => (
                                <div key={i} className="bg-gray-50 rounded-2xl p-6 border border-gray-100 hover:border-eyecare-blue/30 transition-colors h-full">
                                    <div className="w-12 h-12 rounded-full bg-blue-100 flex items-center justify-center text-eyecare-blue mb-4">
                                        {item.icon}
                                    </div>
                                    <h3 className="font-bold text-lg text-eyecare-navy mb-2">{item.title}</h3>
                                    <p className="text-gray-600 leading-relaxed text-sm">{item.desc}</p>
                                </div>
                            ))}
                        </div>
                    </div>
                </div>
            </section>

            {/* CityPrevalence - supporting data for Why Choose Us */}
            <CityPrevalence
                citySlug={city.slug}
                cityName={city.name}
            />

            {/* ================================================================ */}
            {/* SECTION 7: CityCommuteSection                                    */}
            {/* Replaces generic map with accurate commute data                  */}
            {/* ================================================================ */}
            <CityCommuteSection
                citySlug={city.slug}
                cityName={city.name}
                coordinates={city.coordinates}
            />

            {/* ================================================================ */}
            {/* SECTION 8: CityFAQSection                                        */}
            {/* Visible FAQ accordion with FAQPage schema                        */}
            {/* ================================================================ */}
            <CityFAQSection
                citySlug={city.slug}
                cityName={city.name}
                county={city.county}
            />

            {/* ================================================================ */}
            {/* SECTION 9: CityInsuranceSection                                  */}
            {/* City-type-aware insurance messaging                              */}
            {/* ================================================================ */}
            <CityInsuranceSection
                citySlug={city.slug}
                cityName={city.name}
            />

            {/* ================================================================ */}
            {/* SECTION 10: Lead Form                                            */}
            {/* KEPT from original                                               */}
            {/* ================================================================ */}
            <LeadForm />

            {/* ================================================================ */}
            {/* SECTION 11: Keratoconus Education Snippet                        */}
            {/* Links to resources page for internal linking value                */}
            {/* ================================================================ */}
            <KeratoconusEducationSnippet
                cityName={city.name}
            />
        </>
    );
}
